name: Timeout
options:
  minimumXcodeGenVersion: 2.45.0
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: NO
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    MARKETING_VERSION: 0.1.0
    PRODUCT_BUNDLE_IDENTIFIER: com.mentimeter.timeout
    SWIFT_VERSION: 6.0
targets:
  Timeout:
    type: application
    platform: macOS
    sources:
      - path: Timeout
    settings:
      base:
        INFOPLIST_FILE: Timeout/Info.plist
        PRODUCT_NAME: "Timeout!"

